version: "2.4"
services:
  frontend:
    image: jihogrammer/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m
    # build:
    #   dockerfile: dockerfile.dev
    #   context: ./frontend
  nginx:
    restart: always
    image: jihogrammer/docker-nginx
    ports:
      - "80:80"
    links:
      - frontend
      - backend
    mem_limit: 128m
    # build:
    #   dockerfile: dockerfile
    #   context: ./nginx
  backend:
    image: jihogrammer/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: docker-fullstack-mysql.cdlor9chrfkp.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    mem_limit: 128m
    # build:
    #   dockerfile: dockerfile.dev
    #   context: ./backend