version: 2.4
services:
  frontend:
    image: jihogrammer/docker-frontend
    build:
      dockerfile: dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
  nginx:
    restart: always
    image: jihogrammer/docker-nginx
    build:
      dockerfile: dockerfile
      context: ./nginx
    ports:
      - "3000:80"
  backend:
    image: jihogrammer/docker-backend
    container_name: app_backend
    build:
      dockerfile: dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: docker-fullstack-mysql.cdlor9chrfkp.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306